CREATE DATABASE BACHELOR_LOGIN_DB;
CREATE TABLE LOGIN_TBLE
(
USERNAME VARCHAR (50)NOT NULL,
PASS NVARCHAR(50)NOT NULL, 
);
SELECT * FROM LOGIN_TBLE;
INSERT INTO LOGIN_TBLE VALUES ('ADMIN','admin');
CREATE TABLE HOME_TBLE
(
USERNAME VARCHAR (50)NOT NULL,
PASS NVARCHAR(50)NOT NULL, 
);
SELECT * FROM HOME_TBLE;
INSERT INTO HOME_TBLE VALUES ('HOMEOWNER','home');
CREATE TABLE EMPLOYEE_DETAILS
(
FIRST_NAME VARCHAR (50),
SECOND_NAME VARCHAR (50),
OCCUPATION  VARCHAR (50),
NID_NUMBER VARCHAR (50),
BLOOD_GROUP VARCHAR (50),
Contact_NUMBER VARCHAR (50),
Emergency_Contact_NUMBER  VARCHAR (50),
ADDRES VARCHAR (50),
Institution_Name VARCHAR (50),
EMAIL VARCHAR (50),
PICTURE IMAGE,
NID_PICTURE IMAGE ,
USERNAME VARCHAR(50),
PASS VARCHAR(50)
);
SELECT * FROM EMPLOYEE_DETAILS;
CREATE TABLE ROOM
(
RoomNo varchar(100) not null  unique  ,
RoomType varchar(100)not null ,
Bed varchar(100) not null,
Price int 
);
select * from ROOM;
CREATE TABLE findHome
(
FIRST_NAME VARCHAR (50),
SECOND_NAME VARCHAR (50),
NID_NUMBER VARCHAR (50),
Mobile_NUMBER VARCHAR (50),
ADDRES VARCHAR (50),
Check_in VARCHAR(50) not null,
RoomNo varchar(100) not null  unique ,
foreign key (RoomNo) references  ROOM(RoomNo)
);
select * from findHome;